name: centrifuge
version: 0.6.0

description: >
  Dart client to communicate with Centrifuge and Centrifugo from Flutter and VM over import 'package:universal_io/io.dart'; WebSocket

homepage: http://github.com/centrifugal/centrifuge-dart

environment:
 sdk: '>=2.12.0 <3.0.0'

dependencies:
 meta: ^1.3.0
 protobuf: ^2.0.0
 fixnum: ^1.0.0
 universal_io: ^2.0.4

dev_dependencies:
  test: ^1.17.4
  mockito: ^5.0.7
  build_runner: ^2.0.3
